### ISSUE TITLE
Update difftest mechanisms to be integrated directly into endpoints that require it

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/paradigm#16]

**Comment by JosephMcArthur** [comment]
Can we discuss this on Wednesday?

**Comment by JosephMcArthur** [comment]
This doesn't need to use the sheet we'd made (even the API ones in there), or do anything fancy for Joe. Whatever is needed for Mark is good enough. Much of the scope of this can be managed by Ghostinspector (which isn't designed for this but I've tested that it'll work okay).

**Comment by markmacgillivray** [comment]
Still to attach some notifications to the logging of these, so moving to next milestone.

**Comment by markmacgillivray** [comment]
Nothing new to report here

**Comment by markmacgillivray** [comment]
No specific requirements for this, a possible new service has been found to fill the gap if still desired on the API testing side, otherwise ghost has covered all the UI-side bases (which indirectly confirms API output)
