### ISSUE TITLE
Move all parts necessary for covidpapers into paradigm

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/paradigm#23]
Joe has directly asked to keep covidpapers running, and there is still occasional use by others, so will need to move it across at some point too.

**Comment by markmacgillivray** [comment]
@JosephMcArthur we have still not done or prioritised this, and it has been almost a year since covidpapers was updated. Is there still any need to move it over, or shall we let it go?

**Comment by JosephMcArthur** [comment]
Let it go
