### ISSUE TITLE
Return file url on disk/s3 as result from wrapper

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/paradigm#26]

**Comment by markmacgillivray** [comment]
The old way of uploading to the server should still be possible with the backend, but is limiting in terms of our new resiliency goals. amazon s3 have since integrated the old approach of "make a random-named bucket open, let a user upload to it, then make it not open" into something that can be done properly via their permissions API. So move to using that.

**Comment by JosephMcArthur** [comment]
This is related to deposit, right? If so, I'd say lets stick it in the tracker issue but move it out of September. I think it's pretty unlikely we start the refactor in September.

**Comment by markmacgillivray** [comment]
CF now have a beta file handling feature too. However, we also don't have a specific requirement for this yet - as long as file requests to CF successfully hand off to background, and the background passes off to zenodo or other third party repo, we don't have any need for "local/cloud" file management ourselves. I'll keep this open and assigned for now, until it is at least discussed and then closed or scheduled.

**Comment by JosephMcArthur** [comment]
I'm happy for this to be closed, there is not a firm requirement right now and if there was it may be better to take it via CF anyway.
