### ISSUE TITLE
Make our own reliable index of journals

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/paradigm#43]

**Comment by JosephMcArthur** [comment]
Noting from discussion.

Unpaywall are putting together something in the realm of this with JournalsDB / OpenAlex. I suggest we do not invest much time in this.

**Comment by markmacgillivray** [comment]
Agreed not doing much here, but keeping open and moving into next milestone to keep it on my mind while keeping an eye on how we're using all the latest datasets, and doing Gates analysis.
